# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -fno-builtin-strspn -fno-builtin-strcspn -fno-builtin-strpbrk
CXXFLAGS = -Wall -Wextra -Oz -fno-builtin-strspn -fno-builtin-strcspn -fno-builtin-strpbrk

# ----------------------------

include $(shell cedev-config --makefile)
