# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "strlcpy test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -O0
CXXFLAGS = -Wall -Wextra -O0

# ----------------------------

include $(shell cedev-config --makefile)
