# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
DESCRIPTION = "gfx_GetClipRegion test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Wshadow -Oz
CXXFLAGS = -Wall -Wextra -Wshadow -Oz

# ----------------------------

include $(shell cedev-config --makefile)
