.PHONY: clean All

All:
	@echo "----------Building project:[ demo_6 - Debug ]----------"
	@"$(MAKE)" -f  "demo_6.mk"
clean:
	@echo "----------Cleaning project:[ demo_6 - Debug ]----------"
	@"$(MAKE)" -f  "demo_6.mk" clean
