dist: xenial
sudo: required

language: cpp

addons:
  apt:
    packages:
      - wine
      - doxygen
      - doxygen-doc

script:
# Build toolchain and libs
  - export WINEDEBUG=-all
  - export CEDEV=~/CEdev
  - export PATH=$CEDEV/bin/:$PATH
  - export AUTOTESTER_LIBS_DIR=$(pwd)/clibraries
  - make -j4 install release release-libs
# Build examples
  - make -C $CEDEV/examples
# Build CEmu core and autotester_cli
  - git clone --recursive -b latest-stable --depth 1 https://github.com/CE-Programming/CEmu.git
  - make -C CEmu/core -j4
  - make -C CEmu/tests/autotester -j2
  - export PATH=$(pwd)/CEmu/tests/autotester:$PATH
# Grab ROM for tests below
  - export ROM_FILE_NAME=84pce_515_53.rom
  - curl -s https://tiplanet.org/scripts/travis/$ROM_FILE_NAME 2>/dev/null > $ROM_FILE_NAME
  - export AUTOTESTER_ROM=$(pwd)/$ROM_FILE_NAME
# Test toolchain examples
  - RESULT=0; for f in $CEDEV/examples/*/*/*.json; do echo "Launching autotester on $f"; autotester "$f"; RESULT=`expr $RESULT + $?`; done; return $RESULT

after_success:
# Update the funcs_tested file (WIP)
  - ./tools/funcs_tested/gen_list.sh
# Build the doxygen
  - make doxygen
# Update repo files
  - bash .deploy.sh

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true
