version: "{branch}-ci-{build}"

environment:
  matrix:
  - MINGW_ARCH: i686
    MINGW_ROOT: C:\MinGW
    MSYS2_MINGW_ROOT_FOR_CEMU: C:\msys64\mingw32
  - MINGW_ARCH: x86_64
    MINGW_ROOT: C:\msys64\mingw64
    MSYS2_MINGW_ROOT_FOR_CEMU: C:\msys64\mingw64
    USING_MSYS2: yes

install:
  # Recursive checkout
  - git submodule update --init --recursive

  # MinGW
  - set OLD_PATH=%PATH%
  - if defined MINGW_ROOT if not defined USING_MSYS2 set PATH=%MINGW_ROOT%\bin;%PATH%
  - if defined MINGW_ROOT if defined USING_MSYS2 set PATH=%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%
  #- if defined MINGW_ARCH bash -lc "pacman --needed --noconfirm -S mingw-w64-%MINGW_ARCH%-boost mingw-w64-%MINGW_ARCH%-libarchive"

build_script:
  - if defined MINGW_ROOT mingw32-make && mingw32-make install && mingw32-make release-libs
  
  # Some environment variables for later...
  - set CEDEV=C:\CEdev
  - set PATH=%CEDEV%\bin\;%PATH%
  - set AUTOTESTER_LIBS_DIR=%CD%\clibraries
  
  # Build examples
  - if defined MINGW_ROOT make -C %CEDEV%\examples

  # Build CEmu core and autotester_cli
  - git clone --recursive -b latest-stable --depth 1 https://github.com/CE-Programming/CEmu.git
  
  # Workaround for bad bad symlinks (v1.0 seems to have them)
  - if exist CEmu\core\debug\debug.cpp ( move CEmu\core\debug\debug.c CEmu\core\debug\debug.c.old & copy CEmu\core\debug\debug.cpp CEmu\core\debug\debug.c )
  
  # Set env to MSYS2
  - set PATH=%MSYS2_MINGW_ROOT_FOR_CEMU%\bin;C:\msys64\usr\bin\;%OLD_PATH%
  - make -C CEmu/core -j%NUMBER_OF_PROCESSORS%
  - make -C CEmu/tests/autotester -j%NUMBER_OF_PROCESSORS%
  - set PATH=%CD%\CEmu\tests\autotester;%PATH%
  
  # Grab ROM for tests below
  - set ROM_FILE_NAME=84pce_515_53.rom
  - curl -s https://tiplanet.org/scripts/travis/%ROM_FILE_NAME% 2> nul > %ROM_FILE_NAME%
  - set AUTOTESTER_ROM=%CD%\%ROM_FILE_NAME%

  # Test toolchain examples
  - cmd: run_autotester.bat

