# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Os -mllvm -inline-threshold=100 -Wall -Wextra
CXXFLAGS = -Os -mllvm -inline-threshold=100 -Wall -Wextra

# ----------------------------

include $(shell cedev-config --makefile)
