# ----------------------------
# Program Options
# ----------------------------

NAME ?= CPPREAL
ICON ?= icon.png
DESCRIPTION  ?= "ti::real C++ demo"
COMPRESSED ?= NO
ARCHIVED ?= NO

CFLAGS ?= -Wall -Wextra -Oz
CXXFLAGS ?= -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
