# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Wshadow -Oz
CXXFLAGS = -Wall -Wextra -Wshadow -Oz

HAS_PRINTF = YES
PRINTF_NO_FLOAT = YES

# ----------------------------

include $(shell cedev-config --makefile)
