# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Wshadow -Oz
CXXFLAGS = -Wall -Wextra -Wshadow -Oz

PREFER_OS_LIBC = NO
PREFER_OS_CRT = NO
HAS_PRINTF = NO
ALLOCATOR = CUSTOM

# ----------------------------

include $(shell cedev-config --makefile)
