# ----------------------------
# Program Options
# ----------------------------

NAME = CPPREAL
ICON = icon.png
DESCRIPTION  = "ti::real pi montecarlo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
