# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -std=c17 -Oz
CXXFLAGS = -Wall -Wextra -std=c++20 -Oz

PREFER_OS_LIBC = NO
HAS_PRINTF = YES

# ----------------------------

include $(shell cedev-config --makefile)
