# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -ffreestanding -Oz
CXXFLAGS = -Wall -Wextra -ffreestanding -Oz

# ----------------------------

include $(shell cedev-config --makefile)
