# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -DLINKLIB_KEY="\"$(NAME)\""
CXXFLAGS = -Wall -Wextra -Oz -DLINKLIB_KEY="\"$(NAME)\""

# ----------------------------

include $(shell cedev-config --makefile)
