# ----------------------------
# Program Options
# ----------------------------

NAME         ?= HOOKLOG
ICON         ?= icon.png
DESCRIPTION  ?= "Cap'n Hook Test Program"
COMPRESSED   ?= NO
ARCHIVED     ?= NO

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS ?= -Wall -Wextra -Oz

# ----------------------------
# Debug Options
# ----------------------------

OUTPUT_MAP   ?= YES

include $(CEDEV)/meta/makefile.mk
