#!/bin/bash
shopt -s nocasematch
declare -A defs
IFS=$' \t\r\n,'
for file in "$@"; do
    while read -r -a line; do
        if [[ "${#line[@]}" -ge 2 && "${line[0]}" =~ ^.?(global|public|x?def)$ ]]; then
            for ((i = 1; i < ${#line[@]}; i++)); do
                symbol="${line[$i]%:*}"
                if [[ -v "defs[$symbol]" ]]; then
                    printf "Symbol %s is defined multiple times.\n" "$symbol" >&2
                else
                    defs["${line[1]%:*}"]="$file"
                fi
            done
        fi
    done <"$file"
done
for file in "$@"; do
    while read -r -a line; do
        if [[ "${#line[@]}" -ge 2 && "${line[0]}" =~ ^.?(extern(al)?|x?ref)$ ]]; then
            for ((i = 1; i < ${#line[@]}; i++)); do
                symbol="${line[$i]%:*}"
                if [[ -v "defs[$symbol]" ]]; then
                    printf "%s %s\n" "$file" "${defs[$symbol]}"
                else
                    printf "Symbol %s is not defined.\n" "$symbol" >&2
                fi
            done
        fi
    done <"$file"
done | tsort
