# ----------------------------
# Set NAME to the program name
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# Set COMPRESSED to "YES" to create a compressed program
# ----------------------------

NAME        ?= DEMO
COMPRESSED  ?= NO
ICON        ?= iconc.png
DESCRIPTION ?= "C SDK Demo"

# ----------------------------

# This is just so the main makefile in $CEDEV/examples makes this one be like "make debug"
.DEFAULT_GOAL := debug

include $(CEDEV)/include/.makefile
